name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repo
        uses: actions/checkout@v4
      - name: Hello World
        run: echo "hello world"
