name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kod źródłowy
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Logowanie do Docker Hub (lub innego rejestru)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Budowanie obrazu Dockera
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-image-name:latest .

      # 4. Wypchnięcie obrazu do rejestru
      - name: Push Docker image to Docker Hub
        run: |
          docker push your-dockerhub-username/your-image-name:latest
